sudo: false
language: elixir
elixir:
  - 1.6.4
otp_release:
  - 20.3
cache:
  directories:
  - _build
  - deps
addons:
  postgresql: '9.6'
services:
  - postgresql
before_script:
  - psql -c 'create database bookbudget_test;' -U postgres
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
